framework:
    cache:
        # Unique namespace to avoid collisions
        prefix_seed: "technoprod_cache"
        
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deployments.
        # Other options include:

        # Redis (recommended for production)
        app: cache.adapter.redis
        # system: cache.adapter.redis
        
        # APCu (good for single server)
        # app: cache.adapter.apcu
        
        pools:
            # Cache pour les données géographiques (longue durée)
            cache.geographic:
                adapter: cache.adapter.redis
                default_lifetime: 86400  # 24h
                
            # Cache pour les statistiques dashboard (courte durée)
            cache.dashboard:
                adapter: cache.adapter.redis
                default_lifetime: 300  # 5 minutes
                
            # Cache pour les requêtes lourdes (durée moyenne)
            cache.queries:
                adapter: cache.adapter.redis
                default_lifetime: 3600  # 1 heure

        default_redis_provider: 'redis://localhost:6379'